// ── Exercise Library ──────────────────────────────────────────────────────────
// pattern: 'push' | 'pull' | 'legs' | 'core'
// equipment: array of 'barbell' | 'dumbbell' | 'cables' | 'machines' | 'bodyweight'

const EXERCISES = [
  // ── CHEST ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell_bench',
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: ['barbell'],
    pattern: 'push',
    cue: 'Retract scapula and pin it to the bench. Bar path slightly diagonal — touch lower chest, press back toward rack. Drive feet into the floor.',
  },
  {
    id: 'incline_barbell_bench',
    name: 'Incline Barbell Bench Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: ['barbell'],
    pattern: 'push',
    cue: 'Set bench to 30–45°. Keep elbows at ~60° from torso. Touch upper chest. Avoid flaring elbows excessively.',
  },
  {
    id: 'decline_barbell_bench',
    name: 'Decline Barbell Bench Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps'],
    equipment: ['barbell'],
    pattern: 'push',
    cue: 'Targets lower chest. Secure feet firmly. Bar touches below nipple line. Shorter range of motion is normal.',
  },
  {
    id: 'db_bench',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: ['dumbbell'],
    pattern: 'push',
    cue: 'Neutral or pronated grip. Let elbows drop to chest level at bottom. Squeeze at top without fully locking out. Greater stretch than barbell.',
  },
  {
    id: 'incline_db_press',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: ['dumbbell'],
    pattern: 'push',
    cue: '30–45° incline. Dumbbells slightly angled inward at top. Control the descent for full upper chest stretch.',
  },
  {
    id: 'db_fly',
    name: 'Dumbbell Fly',
    muscleGroup: 'Chest',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'push',
    cue: 'Slight bend in elbows throughout — never straighten. Wide arc down, squeeze pecs to bring dumbbells back up. Isolation movement, keep weight conservative.',
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    muscleGroup: 'Chest',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'push',
    cue: 'Set cables at shoulder height. Lean slightly forward. Hug a barrel — round the arms. Constant tension unlike dumbbells. Squeeze hard at crossover.',
  },
  {
    id: 'incline_cable_fly',
    name: 'Incline Cable Fly',
    muscleGroup: 'Chest',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'push',
    cue: 'Set cables low. Targets upper chest. Keep same barrel-hug arc, bringing cables up and together. Squeeze at top.',
  },
  {
    id: 'chest_dip',
    name: 'Chest Dip',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: ['bodyweight'],
    pattern: 'push',
    cue: 'Lean torso forward 15–30° to shift load to chest. Go deep enough to feel stretch in pec, then drive up. Elbows flare slightly outward.',
  },
  {
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps'],
    equipment: ['machines'],
    pattern: 'push',
    cue: 'Adjust seat so handles are at mid-chest. Retract scapula. Good for beginners or as a finisher. Constant tension through full ROM.',
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck',
    muscleGroup: 'Chest',
    secondaryMuscles: [],
    equipment: ['machines'],
    pattern: 'push',
    cue: 'Keep elbows at shoulder height. Don\'t let arms go past the plane of the body. Slow eccentric. Isolation — go for the squeeze.',
  },

  // ── BACK ──────────────────────────────────────────────────────────────────
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Hinge to ~45°, chest up, brace core. Pull bar to lower chest/upper abdomen. Lead with elbows, not hands. Squeeze lats at top. Control descent.',
  },
  {
    id: 'pendlay_row',
    name: 'Pendlay Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Torso parallel to floor. Bar starts on the floor each rep. Explosive pull to lower chest. Builds power and thickness. Strict form critical.',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    muscleGroup: 'Back',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Traps'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Bar over mid-foot. Hip hinge, neutral spine. Push the floor away. Lock out hips and knees simultaneously. Control the descent — don\'t just drop it.',
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    muscleGroup: 'Back',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Quads'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Wide stance, toes out ~45°. Grip inside the legs. More vertical torso than conventional. Drives through hips. Great for those with mobility limitations.',
  },
  {
    id: 'rack_pull',
    name: 'Rack Pull',
    muscleGroup: 'Back',
    secondaryMuscles: ['Traps', 'Glutes'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Bar at knee height. Allows heavier loads — builds upper back and traps. Same mechanics as top half of deadlift. Brace hard.',
  },
  {
    id: 'pullup',
    name: 'Pull-Up',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipment: ['bodyweight'],
    pattern: 'pull',
    cue: 'Overhand grip, slightly wider than shoulder width. Pull chest to bar, not chin. Depress and retract scapula before pulling. Full hang at bottom.',
  },
  {
    id: 'chinup',
    name: 'Chin-Up',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipment: ['bodyweight'],
    pattern: 'pull',
    cue: 'Underhand grip, shoulder-width. More bicep involvement than pull-ups. Same scapular cue. Great for building vertical pulling strength.',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipment: ['cables', 'machines'],
    pattern: 'pull',
    cue: 'Slight lean back, chest up. Pull bar to upper chest, leading with elbows. Squeeze lats hard. Slow return — resist the weight on the way up.',
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    equipment: ['cables'],
    pattern: 'pull',
    cue: 'Sit tall, slight lean. Pull to lower sternum, elbows close to body. Squeeze rhomboids at the end. Don\'t rock torso — use back, not momentum.',
  },
  {
    id: 'single_arm_db_row',
    name: 'Single-Arm Dumbbell Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipment: ['dumbbell'],
    pattern: 'pull',
    cue: 'Brace on bench. Row dumbbell to hip, not shoulder. Think "elbow to pocket". Rotate torso slightly at top. Full stretch at bottom.',
  },
  {
    id: 'tbar_row',
    name: 'T-Bar Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Straddle the bar. Similar to bent-over row but more stable. Pull to sternum. Great for mid-back thickness. Keep chest proud.',
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    muscleGroup: 'Rear Delts',
    secondaryMuscles: ['Traps', 'External Rotators'],
    equipment: ['cables'],
    pattern: 'pull',
    cue: 'Cable at head height, rope attachment. Pull to face with elbows high and flared. Externally rotate at the end (hands finish above elbows). Essential for shoulder health.',
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Straight-Arm Pulldown',
    muscleGroup: 'Back',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'pull',
    cue: 'Arms straight, slight bend. Pull bar from overhead to thighs using lats only. Hinge at shoulder, not elbow. Best lat isolation exercise.',
  },
  {
    id: 'machine_row',
    name: 'Machine Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipment: ['machines'],
    pattern: 'pull',
    cue: 'Chest against pad. Pull handles to sides of chest. Squeeze shoulder blades together. Good for maintaining tension throughout the movement.',
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────────────
  {
    id: 'barbell_ohp',
    name: 'Barbell Overhead Press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest'],
    equipment: ['barbell'],
    pattern: 'push',
    cue: 'Bar rests on front delts. Brace core and glutes. Press straight up, head shifts back to allow bar path. Lock out fully overhead. Bar returns to chin level.',
  },
  {
    id: 'seated_db_press',
    name: 'Seated Dumbbell Press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    equipment: ['dumbbell'],
    pattern: 'push',
    cue: 'Sit at 90° back support. Dumbbells at ear level to start. Press overhead without internally rotating at top. Full lockout. Neutral spine.',
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    equipment: ['dumbbell'],
    pattern: 'push',
    cue: 'Start palms facing you. Rotate to pronated as you press. Hits all three delt heads through rotation. Go lighter than a standard press.',
  },
  {
    id: 'lateral_raise_db',
    name: 'Lateral Raise',
    muscleGroup: 'Shoulders',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'push',
    cue: 'Lead with elbows, not wrists. Slight forward lean and bend in elbows. Raise to shoulder height — not higher. Slow eccentric (3s down). Go lighter than you think.',
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'push',
    cue: 'Cable at low pulley, across body. Constant tension unlike dumbbells — especially at the bottom. Lead with elbow. Same cues as dumbbell version.',
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    muscleGroup: 'Rear Delts',
    secondaryMuscles: ['Traps'],
    equipment: ['dumbbell'],
    pattern: 'pull',
    cue: 'Hinge forward 45°. Arms slightly bent. Lead with elbows, raise to shoulder height. Squeeze rear delts at top. Don\'t use momentum. Often undertrained.',
  },
  {
    id: 'cable_rear_delt_fly',
    name: 'Cable Rear Delt Fly',
    muscleGroup: 'Rear Delts',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'pull',
    cue: 'Cables crossed at head height. Pull handles apart and slightly downward. Constant tension on rear delts. More effective than dumbbell version for most.',
  },
  {
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    equipment: ['machines'],
    pattern: 'push',
    cue: 'Adjust seat so handles are at shoulder level. Press directly overhead. Good for high-rep work or when fatigued. Reduces stabiliser demand.',
  },

  // ── BICEPS ────────────────────────────────────────────────────────────────
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Elbows pinned to sides. Full extension at bottom, full contraction at top. Don\'t swing. Supinate (rotate) wrists fully as you curl.',
  },
  {
    id: 'ezbar_curl',
    name: 'EZ-Bar Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: ['barbell'],
    pattern: 'pull',
    cue: 'Semi-supinated grip reduces wrist strain. Same mechanics as barbell curl. Slightly reduced bicep activation vs straight bar but more comfortable.',
  },
  {
    id: 'db_curl',
    name: 'Dumbbell Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: ['dumbbell'],
    pattern: 'pull',
    cue: 'Alternate or simultaneous. Supinate as you curl. Full range of motion. Don\'t let elbows drift forward at top — keep them at your sides.',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: ['Brachialis', 'Forearms'],
    equipment: ['dumbbell'],
    pattern: 'pull',
    cue: 'Neutral (hammer) grip throughout. Targets brachialis and brachioradialis more than supinated curl. Builds arm thickness. Elbows stay pinned.',
  },
  {
    id: 'incline_db_curl',
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'pull',
    cue: 'Sit on incline bench, arms hang straight down. Maximises long head stretch. Don\'t swing. Allow full hang at bottom. Excellent for peak.',
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'pull',
    cue: 'Low pulley. Curl with constant cable tension — superior to dumbbells in the contracted position. Can be done one or two arms.',
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: [],
    equipment: ['machines'],
    pattern: 'pull',
    cue: 'Arm braced on pad — eliminates cheating. Feel the stretch at full extension. Don\'t hyperextend at the bottom. Short head emphasis.',
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    pattern: 'pull',
    cue: 'Seated, elbow braced on inner thigh. Full supination at top. Slow and controlled. Pure isolation — no cheating possible. Great finisher.',
  },

  // ── TRICEPS ───────────────────────────────────────────────────────────────
  {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    muscleGroup: 'Triceps',
    secondaryMuscles: ['Chest', 'Shoulders'],
    equipment: ['barbell'],
    pattern: 'push',
    cue: 'Grip shoulder-width (not ultra-narrow). Elbows tucked close to body. Same path as bench press. Heavy compound movement for tricep mass.',
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    muscleGroup: 'Triceps',
    secondaryMuscles: [],
    equipment: ['barbell'],
    pattern: 'push',
    cue: 'EZ-bar or straight bar. Lower to forehead or behind head. Only move at the elbow — upper arm stays vertical. Long head stretch is the goal.',
  },
  {
    id: 'tricep_dip',
    name: 'Tricep Dip',
    muscleGroup: 'Triceps',
    secondaryMuscles: ['Chest', 'Shoulders'],
    equipment: ['bodyweight'],
    pattern: 'push',
    cue: 'Keep torso upright (unlike chest dip). Elbows directly behind you. Lower until upper arm is parallel to floor. Lock out fully at top.',
  },
  {
    id: 'cable_pushdown',
    name: 'Cable Tricep Pushdown',
    muscleGroup: 'Triceps',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'push',
    cue: 'Elbows pinned at sides. Only lower arm moves. Full extension at bottom, don\'t let upper arm drift forward. Rope or bar attachment both work.',
  },
  {
    id: 'overhead_tricep_ext',
    name: 'Overhead Tricep Extension',
    muscleGroup: 'Triceps',
    secondaryMuscles: [],
    equipment: ['dumbbell', 'cables'],
    pattern: 'push',
    cue: 'Arms overhead, elbows by ears. Maximises long head stretch — the largest of three tricep heads. Keep upper arms vertical throughout.',
  },
  {
    id: 'machine_tricep_ext',
    name: 'Machine Tricep Extension',
    muscleGroup: 'Triceps',
    secondaryMuscles: [],
    equipment: ['machines'],
    pattern: 'push',
    cue: 'Adjust pad for your arm length. Full extension at bottom. Good for pump work and high reps. Consistent resistance curve.',
  },

  // ── LEGS ──────────────────────────────────────────────────────────────────
  {
    id: 'back_squat',
    name: 'Barbell Back Squat',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: ['barbell'],
    pattern: 'legs',
    cue: 'Bar on traps (high bar) or rear delts (low bar). Brace hard. Knees track toes. Hit depth (hip crease below knee). Drive through full foot, not just heels.',
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes', 'Core'],
    equipment: ['barbell'],
    pattern: 'legs',
    cue: 'Bar on front delts, elbows high. More upright torso than back squat. Greater quad emphasis. Demands thoracic mobility. Clean grip or cross-arm grip.',
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    muscleGroup: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Back'],
    equipment: ['barbell'],
    pattern: 'legs',
    cue: 'Hinge from hips, slight knee bend. Bar stays close to legs. Feel hamstring stretch — go to comfortable depth (not floor). Squeeze glutes to return. No rounding.',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: ['machines'],
    pattern: 'legs',
    cue: 'Foot position changes emphasis: high = more glute/ham, low = more quad. Don\'t lock knees out fully. Never release the safety without straightening legs first.',
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    muscleGroup: 'Hamstrings',
    secondaryMuscles: [],
    equipment: ['machines'],
    pattern: 'legs',
    cue: 'Lying or seated. Full extension at start, full curl at end. Plantarflex (point toes) to maximise hamstring contraction. Slow eccentric for growth.',
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    muscleGroup: 'Quads',
    secondaryMuscles: [],
    equipment: ['machines'],
    pattern: 'legs',
    cue: 'Pad on lower shin, not ankle. Full extension at top — squeeze quads. Slow eccentric. Some knee sensitivity; if discomfort, reduce range.',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: ['dumbbell', 'barbell'],
    pattern: 'legs',
    cue: 'Rear foot elevated on bench. Front foot far enough forward that torso can stay upright. Lower back knee toward floor. Hardest leg exercise — reduces load accordingly.',
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    pattern: 'legs',
    cue: 'Big step forward. Lower back knee toward (not touching) ground. Keep front shin vertical. Drive through front heel to step through.',
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes'],
    equipment: ['machines'],
    pattern: 'legs',
    cue: 'Feet low and close for maximum quad activation. Full depth. Machine guides the path so more load can be used safely. Great quad builder.',
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    muscleGroup: 'Glutes',
    secondaryMuscles: ['Hamstrings'],
    equipment: ['barbell'],
    pattern: 'legs',
    cue: 'Upper back on bench edge, bar on hip crease (use pad). Chin tucked, drive hips up, squeeze glutes hard at top. Posterior pelvic tilt at lockout. Best glute builder.',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    muscleGroup: 'Quads',
    secondaryMuscles: ['Glutes', 'Core'],
    equipment: ['dumbbell'],
    pattern: 'legs',
    cue: 'Hold dumbbell at chest. Counterbalance allows more upright torso. Elbows inside knees at bottom. Great for mobility and as a warm-up/accessory.',
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    muscleGroup: 'Calves',
    secondaryMuscles: [],
    equipment: ['machines', 'bodyweight'],
    pattern: 'legs',
    cue: 'Full range — stretch at bottom, squeeze at top. Slow tempo (2-2-2). Go heavy with higher reps (15–20). Calves are stubborn — volume is key.',
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Curl',
    muscleGroup: 'Hamstrings',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'legs',
    cue: 'Kneel, feet anchored. Lower body as slowly as possible toward floor. Use hands to catch/push back up. One of the best hamstring exercises — very demanding.',
  },

  // ── CORE ──────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    muscleGroup: 'Core',
    secondaryMuscles: ['Shoulders'],
    equipment: ['bodyweight'],
    pattern: 'core',
    cue: 'Forearms or hands. Squeeze glutes, brace core — think "protect against a punch". Neutral spine, don\'t let hips sag or pike. Breathe.',
  },
  {
    id: 'ab_wheel',
    name: 'Ab Wheel Rollout',
    muscleGroup: 'Core',
    secondaryMuscles: ['Lats', 'Shoulders'],
    equipment: ['bodyweight'],
    pattern: 'core',
    cue: 'Kneel on mat. Roll out as far as you can maintain a hollow body position. Roll back by pulling navel to spine. Don\'t hyperextend lower back.',
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    muscleGroup: 'Core',
    secondaryMuscles: ['Hip Flexors'],
    equipment: ['bodyweight'],
    pattern: 'core',
    cue: 'Dead hang, no swing. Raise legs to 90° (or higher). Control the descent. For lower abs — keep legs straighter. Posterior pelvic tilt at the top.',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    muscleGroup: 'Core',
    secondaryMuscles: [],
    equipment: ['cables'],
    pattern: 'core',
    cue: 'Kneel at cable tower, rope at head. Crunch elbow to knee — don\'t just bow forward from hips. Feel abs shorten. Good for progressive overload on abs.',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    muscleGroup: 'Core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    pattern: 'core',
    cue: 'Lie on back, arms up, knees at 90°. Lower opposite arm and leg toward floor while pressing lower back into ground. Anti-extension core stability.',
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    muscleGroup: 'Core',
    secondaryMuscles: ['Obliques'],
    equipment: ['bodyweight', 'dumbbell'],
    pattern: 'core',
    cue: 'Sit at 45°, feet raised or on floor. Rotate torso side to side — not just the arms. Hold a weight for progression. Targets obliques.',
  },
];

// ── Muscle groups for filtering ───────────────────────────────────────────────
const MUSCLE_GROUPS = [...new Set(EXERCISES.map(e => e.muscleGroup))].sort();

// ── Equipment types for filtering ─────────────────────────────────────────────
const EQUIPMENT_TYPES = ['barbell', 'dumbbell', 'cables', 'machines', 'bodyweight'];

// ── Search helper ─────────────────────────────────────────────────────────────
function searchExercises({ query = '', muscleGroup = '', equipment = '' } = {}) {
  return EXERCISES.filter(ex => {
    const matchQuery = !query || ex.name.toLowerCase().includes(query.toLowerCase())
      || ex.muscleGroup.toLowerCase().includes(query.toLowerCase());
    const matchMuscle = !muscleGroup || ex.muscleGroup === muscleGroup;
    const matchEquip = !equipment || ex.equipment.includes(equipment);
    return matchQuery && matchMuscle && matchEquip;
  });
}
