// ── Pre-built Program Presets ─────────────────────────────────────────────────

const PRESETS = [
  {
    id: 'volleyball_foundation',
    name: 'Volleyball Foundation',
    description: '2-day/week programme focused on the athletic base for volleyball — power, single-leg stability, explosive strength.',
    daysPerWeek: 2,
    goal: 'athletic',
    tags: ['Volleyball', 'Power', 'Athletic'],
    days: [
      {
        id: 'vb_session1',
        name: 'Session 1',
        focus: 'Legs, Shoulders & Chest',
        exercises: [
          {
            id: 'front_squat',
            name: 'Front Squat',
            muscleGroup: 'Quads',
            cue: 'Bar on front delts, elbows high. More upright torso than back squat. Greater quad emphasis. Demands thoracic mobility. Clean grip or cross-arm grip.',
            sets: 3,
            reps: '12',
            weight: 60,
          },
          {
            id: 'side_lunge',
            name: 'Side Lunge',
            muscleGroup: 'Quads',
            cue: 'Step wide to one side, pushing hips back and down into the lunge. Keep chest up and grounded foot flat. Inner thigh and glute stretch at bottom. Drive through heel to return. Key for lateral athletic movement.',
            sets: 3,
            reps: '10',
            weight: 0,
          },
          {
            id: 'barbell_ohp',
            name: 'Shoulder Press',
            muscleGroup: 'Shoulders',
            cue: 'Bar rests on front delts. Brace core and glutes. Press straight up, head shifts back to allow bar path. Lock out fully overhead. Bar returns to chin level.',
            sets: 3,
            reps: '10',
            weight: 50,
          },
          {
            id: 'db_bench',
            name: 'DB Chest Press',
            muscleGroup: 'Chest',
            cue: 'Neutral or pronated grip. Let elbows drop to chest level at bottom. Squeeze at top without fully locking out. Greater stretch than barbell.',
            sets: 3,
            reps: '12',
            weight: 22,
          },
          {
            id: 'single_leg_tband_pull',
            name: 'Single Leg T-Band Pull',
            muscleGroup: 'Glutes',
            cue: 'Anchor a resistance band at foot height. Stand on one leg, slight knee bend. Pull the band back behind you in a controlled hip extension while maintaining balance. Challenges single-leg stability critical for landing mechanics in volleyball. Keep hips level throughout — don\'t rotate.',
            sets: 3,
            reps: '10',
            weight: 0,
          },
        ],
      },
      {
        id: 'vb_session2',
        name: 'Session 2',
        focus: 'Power & Back',
        exercises: [
          {
            id: 'deadlift',
            name: 'Deadlift',
            muscleGroup: 'Back',
            cue: 'Bar over mid-foot. Hip hinge, neutral spine. Push the floor away. Lock out hips and knees simultaneously. Control the descent — don\'t just drop it.',
            sets: 3,
            reps: '8',
            weight: 100,
          },
          {
            id: 'power_shrug',
            name: 'Power Shrug',
            muscleGroup: 'Traps',
            cue: 'Start position like a deadlift. Explosively extend hips, knees and ankles (triple extension) then shrug shoulders hard upward. Let the momentum carry the bar — don\'t pull with arms. Trains the power transfer from legs to upper body used in jumping and spiking.',
            sets: 4,
            reps: '6',
            weight: 80,
          },
          {
            id: 'barbell_row',
            name: 'Bent Over Row',
            muscleGroup: 'Back',
            cue: 'Hinge to ~45°, chest up, brace core. Pull bar to lower chest/upper abdomen. Lead with elbows, not hands. Squeeze lats at top. Control descent.',
            sets: 3,
            reps: '10',
            weight: 70,
          },
          {
            id: 'box_jump',
            name: 'Box Jump 24"',
            muscleGroup: 'Quads',
            cue: 'Stand arms-length from box. Dip and swing arms, then explode upward — land softly with bent knees in a squat position. Step down (don\'t jump down) to protect knees. Focus on maximal intent on every rep. Rest fully between sets — this is power work, not cardio.',
            sets: 5,
            reps: '5',
            weight: 0,
          },
        ],
      },
    ],
    progression: {
      week1: 'Foundation — establish movement patterns at moderate load (3×12 Session 1, 3×10 Session 2)',
      week2: 'Volume increase — shoulder press drops to 3×8, bent over row increases to 3×12',
      week3: 'Intensity increase — front squat to 3×10, side lunge to 4×10, bent over row to 4×10',
      week4: 'Peak — front squat to 4×8 at highest load. Consolidation before deload or next block',
    },
  },
];
